HomeWork/HomeWork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('news/', include('NewsPortal.urls'))
]

HomeWork/news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('news/', include('NewsPortal.urls'))
]

HomeWork/NewsPortal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name.username

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.name.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.rating = pRat * 3 + cRat
        self.save()

class Category(models.Model):

    category_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.category_name.title()


class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'

    CATEGORY = [(NEWS, 'Новость'),
                (ARTICLE, 'Статья')
                ]

    category_post = models.CharField(max_length=2, choices=CATEGORY, default=ARTICLE)
    date_time = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)
    added_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, through='PostCategory', related_name='article')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'{self.title.title()}: {self.text}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)




class Comment(models.Model):
    comment = models.TextField()
    time_comment = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to="Category",
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

HomeWork/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Добавить статью</h1>
    <form action="" method="post"/>
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Сохранить"/>
    </form>
{% endblock content %}

HomeWork/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Удаление статьи</h1>
    <form action="" method="post"/>
        {% csrf_token %}
        <p> "Удаляем статью {{ object.title }}?"</p>
    <input type="submit" value="Удалить"/>
    </form>
{% endblock content %}

HomeWork/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Внести изменения в статью</h1>
    <form action="" method="post" />
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
{% endblock content %}

HomeWork/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
  <h2>Здравствуйте! Новые статьи за прошедшую неделю</h2>
  <ul>
    {% for post in posts %}
      <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
</body>
</html>

HomeWork/templates/news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все новости</h1>
<h3> Всего публикаций: {{ news|length}} </h3>
{% if perms.NewsPortal.add_post %}
    <a href="{% url 'post_create' %}">Добавить новость</a>
    <a href="{% url 'article_create' %}">Добавить статью</a>
{% endif %}
    {% if news %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Текст</td>
                <td>Действия</td>
            </tr>
            {% for i in news %}
            <tr>
                <td>{{ i.title|censor }}</td>
                <td>{{ i.date_time|date:'d M Y' }}</td>
                <td>{{ i.text|truncatechars:20|censor }}</td>

                <td>
                {% if i.category_post == 'NW' %}
                    {% if perms.NewsPortal.change_post %}
                        <a href="{% url 'news_edit' i.id %} ">Изменить</a>
                    {% endif %}
                    {% if perms.NewsPortal.delete_post %}
                        <a href="{% url 'news_delete' i.id %} ">Удалить</a>
                    {% endif %}
                {% else %}
                    {% if perms.NewsPortal.change_post %}
                        <a href="{% url 'article_edit' i.id %} ">Изменить</a>
                    {% endif %}
                    {% if perms.NewsPortal.delete_post %}
                        <a href="{% url 'article_delete' i.id %} ">Удалить</a>
                    {% endif %}
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        Новостей нет!
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock content %}

HomeWork/templates/news_create.html
{% extends 'flatpages/default.html'%}



{% block content %}

    <h1>Добавить новость </h1>
    <form action="" method="post"/>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"  value="Сохранить"/>
    </form>


{% endblock content %}

HomeWork/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <form action="" method="post"/>
          {% csrf_token %}
          <p>"Удаляем {{ object.title }}?"</p>
    <input type="submit" value="Удалить"/>
    </form>
{% endblock content %}

HomeWork/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Добавить изменения в новость</h1>
    <form action="" method="post"/>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить"/>
    </form>
{% endblock content %}

HomeWork/templates/news_index.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
    {% if news %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Текст</td>
            </tr>
            <tr>
                <td>{{news.title|censor}}</td>
                <td>{{news.date_time|date:'d M Y'}}</td>
                <td>{{news.text|censor}}</td>
            </tr>
        </table>
    {% endif %}
{% endblock content %}

HomeWork/templates/news_search.html
{% extends 'flatpages/default.html'%}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}

    <h1>Поиск новостей и статей</h1>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" class="mt-3 btn-primary" value="Найти"/>
    </form>

    {% if news %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Текст</td>
            </tr>
            {% for i in news %}
            <tr>
                <td>{{ i.title|censor }}</td>
                <td>{{ i.date_time|date:'d M Y' }}</td>
                <td>{{ i.text|truncatechars:20|censor }}</td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        Новостей нет!
    {% endif %}
{% endblock content %}

HomeWork/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новая <a href="{{ link }}">статья</a> в вашей подборке!</h2>
    <p>{{ text }}</p>
</body>
</html>

HomeWork/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{%block title%}
    Подписки
{% endblock title %}

{% block content %}
    {% for category in categories %}
        <p>
            {{ category.category_name }}
            <form method="post">
            {% csrf_token %}
            <input type="hidden" name="category_id" value="{{ category.id }}"/>

            {% if category.user_subscribed %}
                <button disabled>Подписаться</button>
                <button name="action" value="unsubscribe">Отписаться</button>
            {% else %}
                <button name="action" value="subscribe">Подписаться</button>
                <button disabled>Отписаться</button>
            {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}